### ISSUE TITLE
No dumps or sql/dumps directories?

### ISSUE THREAD

**Issue by bnaught0n** [netherfoam/Titan#98]
I am trying to configure the mysql database (following the instructions using Sequel Pro, the cloned files and mysql db on a nas container) and cannot execute the batch files: 

**Project_Root\sql\dumps\mysql_world.sql -> Start -> Wait
- Repeat above step for file Project_Root\dumps\mysql_logon.sql**

As I see no sql/dumps nor dumps under the root "Titan" directory. Am I stupid, am I missing something?

**Comment by netherfoam** [comment]
So when you first boot, they should run.

You'll just need to configure the database credentials and execute the CREATE DATABASE statement yourself

**Comment by netherfoam** [comment]
I restructured some files but this should be the folder of queries that get run [here](https://github.com/netherfoam/Titan/tree/master/src/main/resources/db/migration)

But they should run automatically when you boot... If you run them manually it'll probably cause problems

**Comment by netherfoam** [comment]
(They only run the first time you boot)

**Comment by bnaught0n** [comment]
Thanks, I'll test it out tomorrow
